# Generated by Django 6.0.2 on 2026-02-24 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentorg', '0003_alter_college_id_alter_organization_id_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrgMember',
            new_name='Member',
        ),
        migrations.AlterField(
            model_name='program',
            name='prog_name',
            field=models.CharField(max_length=150, verbose_name='Program name'),
        ),
        migrations.AlterField(
            model_name='student',
            name='firstname',
            field=models.CharField(max_length=25, verbose_name='First name'),
        ),
        migrations.AlterField(
            model_name='student',
            name='lastname',
            field=models.CharField(max_length=25, verbose_name='Last name'),
        ),
        migrations.AlterField(
            model_name='student',
            name='middlename',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Middle name'),
        ),
    ]
